#!/usr/bin/env zsh

qa() {
  if [[ "$1" == "-h" ]]; then
    echo "Apply a set of kustomize folders (and check which resources have been updated).\n\nUsage: qa FOLDER_1 [FOLDER_2 ...]\nE.g.: \`qa deployment-values/blah\`"
    return
  fi

  for dir in $@; do
    echo "Applying ${dir}"
    kubectl apply -k ${dir} | grep --color -v unchanged
  done
}
